# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "pip"
    directory: "backend/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
