version: "3.8"
name: yjdh-benefit
services:
  postgres:
    build:
      context: ./backend
      dockerfile: ./docker/finnish_postgres.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: benefit
      POSTGRES_PASSWORD: benefit
      POSTGRES_DB: benefit
      LC_COLLATE: "fi_FI.UTF-8"
      LC_CTYPE: "fi_FI.UTF-8"
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: benefit-db

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/benefit-arm.Dockerfile
      target: development
    env_file:
      - .env.benefit-backend
    environment:
      DATABASE_URL: postgres://benefit:benefit@benefit-db/benefit
      DATABASE_HOST: benefit-db.helsinki
    volumes:
      - ./backend/benefit:/app
      - ./backend/shared:/shared
    depends_on:
      - postgres
    container_name: benefit-backend

  local-proxy:
    depends_on:
      - postgres
      - backend
    build:
      context: ./localdevelopment/benefit/nginx
    container_name: benefit-local-proxy
    volumes:
      - ./localdevelopment/benefit/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000

  mailhog:
    image: "mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea"
    ports:
      - 1025:1025
      - 8025:8025
    container_name: benefit-mailhog
    networks:
      - default

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
