version: "3.8"
name: yjdh-tet
services:
  postgres:
    build:
      dockerfile: ./docker/finnish_postgres.Dockerfile
      context: ./backend
    platform: linux/amd64
    restart: on-failure
    environment:
      POSTGRES_USER: tet
      POSTGRES_PASSWORD: tet
      POSTGRES_DB: tet
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: te-db

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/tet.Dockerfile
      target: development
    platform: linux/amd64
    env_file:
      - .env.tet
    environment:
      DATABASE_URL: postgres://tet:tet@te-db/tet
      DATABASE_HOST: te-db.helsinki
    volumes:
      - ./backend/tet:/app
      - ./backend/shared:/shared
      - ./backend/tet/media:/var/media
    depends_on:
      - postgres
    container_name: te-backend

  youth:
    build:
      context: ./frontend
      target: development
      args:
        PORT: 3000
        PROJECT: tet
        FOLDER: youth
    platform: linux/amd64
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.tet
    environment:
      NEXT_PUBLIC_MOCK_FLAG: 1
    container_name: te-youth

  local-proxy:
    depends_on:
      - postgres
      - backend
      - youth
    build:
      context: ./localdevelopment/tet-youth/nginx
    platform: linux/amd64
    container_name: te-local-proxy
    volumes:
      - ./localdevelopment/tet-youth/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:3001:3001

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
