version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: benefit
      POSTGRES_PASSWORD: benefit
      POSTGRES_DB: benefit
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: benefit-db

  django:
    build:
      context: ./backend
      dockerfile: ./docker/benefit.Dockerfile
      target: development
    env_file:
      - .env.benefit-backend
    environment:
      DATABASE_URL: postgres://benefit:benefit@benefit-db/benefit
      DATABASE_HOST: benefit-db.helsinki
    volumes:
      - ./backend/benefit:/app
      - ./backend/shared:/shared
    depends_on:
      - postgres
    container_name: benefit-backend

  applicant:
    build:
      context: ./frontend
      dockerfile: benefit/applicant/Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.benefit-applicant
    container_name: benefit-applicant

  handler:
    build:
      context: ./frontend
      dockerfile: benefit/handler/Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.benefit-handler
    container_name: benefit-handler

  local-proxy:
    depends_on:
      - postgres
      - django
      - applicant
      - handler
    build:
      context: ./localdevelopment/benefit/nginx
    container_name: benefit-local-proxy
    volumes:
      - ./localdevelopment/benefit/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3100:3100

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
