version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: tet
      POSTGRES_PASSWORD: tet
      POSTGRES_DB: tet
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: te-db

  te-bknd:
    build:
      context: ./backend
      dockerfile: ./docker/tet.Dockerfile
      target: development
    env_file:
      - .env.tet
    environment:
      DATABASE_URL: postgres://tet:tet@te-db/tet
      DATABASE_HOST: te-db.helsinki
    volumes:
      - ./backend/tet:/app
      - ./backend/shared:/shared
      - ./backend/tet/media:/var/media
    depends_on:
      - postgres
    container_name: te-bknd

  te-admn:
     build:
       context: ./frontend
       target: development
       args:
         PORT: 3000
         PROJECT: tet
         FOLDER: admin
     volumes:
       - ./frontend:/app
       - /app/node_modules
       - /app/.next
     env_file:
       - .env.tet
     environment:
       NEXT_PUBLIC_MOCK_FLAG: 1
     container_name: te-admn

  te-local-proxy:
    depends_on:
      - postgres
      - te-bknd
      - te-admn
    build:
      context: ./localdevelopment/tet-admin/nginx
    container_name: te-local-proxy
    volumes:
      - ./localdevelopment/tet-admin/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:3002:3002

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
