version: "3.8"
services:
  postgres:
    image: postgres:12
    restart: on-failure
    environment:
      POSTGRES_USER: kesaseteli
      POSTGRES_PASSWORD: kesaseteli
      POSTGRES_DB: kesaseteli
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: kesaseteli-db

  kesaseteli-backend:
    build:
      context: ./backend
      dockerfile: ./docker/kesaseteli.Dockerfile
      target: development
    env_file:
      - .env.kesaseteli
    environment:
      DATABASE_URL: postgres://kesaseteli:kesaseteli@kesaseteli-db/kesaseteli
      DATABASE_HOST: kesaseteli-db.helsinki
    volumes:
      - ./backend/kesaseteli:/app
      - ./backend/shared:/shared
      - ./backend/kesaseteli/media:/var/media
    depends_on:
      - postgres
    container_name: kesaseteli-backend

  kesaseteli-youth:
    build:
      context: ./frontend
      dockerfile: kesaseteli/youth/Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.kesaseteli
    environment:
      - PORT=3100
    container_name: kesaseteli-youth

  kesaseteli-local-proxy:
    depends_on:
      - postgres
      - kesaseteli-backend
      - kesaseteli-youth
    build:
      context: localdevelopment/employer/nginx
    container_name: kesaseteli-local-proxy
    volumes:
      - ./localdevelopment/youth/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:3100:3100

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
