version: '3.7'
services:
    postgres:
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_USER: kesaseteli
            POSTGRES_PASSWORD: kesaseteli
            POSTGRES_DB: kesaseteli
        ports:
            - 5434:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: kesaseteli-db

    django:
        build:
            context: ./backend
            target: development
        env_file:
            - .env
        environment:
            DATABASE_URL: postgres://kesaseteli:kesaseteli@kesaseteli-db/kesaseteli
            DATABASE_HOST: kesaseteli-db.helsinki
        volumes:
            - ./backend:/app
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - postgres
        container_name: kesaseteli-backend

    frontend:
        build:
            context: ./frontend
            dockerfile: kesaseteli/Dockerfile
            target: ${DOCKER_TARGET:-development}
        volumes:
            - ./frontend/kesaseteli:/app/kesaseteli
            - ./frontend/shared:/app/shared
            - /app/node_modules
            - /app/.next
        env_file:
            - .env
        ports:
            - '${KESASETELI_PORT}:${KESASETELI_PORT}'
        container_name: kesaseteli-frontend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
