name: (BF) Python tests

on:
  push:
    branches: [develop, main]
  pull_request:
    paths:
    - 'backend/benefit/**'
    - '.github/workflows/bf-pytest.yml'

env:
  DEBUG: 1

jobs:
  pytest:
    name: Python tests
    runs-on: ubuntu-latest
    container: python:3.8-buster

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: benefit
          POSTGRES_PASSWORD: benefit
          POSTGRES_DB: benefit

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache pip packages
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-modules
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: cd backend/benefit && pip install -r requirements.txt -r requirements-dev.txt codecov

      - name: Run tests
        run: pytest backend/benefit -ra -vv --doctest-modules --cov=. --pyargs shared.oidc
        env:
          DATABASE_URL: postgres://benefit:benefit@postgres/benefit

      - name: Coverage
        run: codecov
