name: (BF) Python coding style

on:
  push:
    branches: [main]
  pull_request:
    paths:
    - 'backend/benefit/**'
    - '.github/workflows/bf-py-coding-style.yml'

env:
  DEBUG: 1

jobs:
  py-coding-style:
    name: Python coding style
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip packages
        uses: actions/cache@v2
        env:
          cache-name: cache-pip-modules
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: cd backend/benefit && pip install -r requirements.txt -r requirements-dev.txt

      - name: Formatting
        run: cd backend/benefit && black --check .

      - name: Linting
        run: cd backend/benefit && flake8 --config ../shared/precommit-setup.cfg

      - name: Import sorting
        run: cd backend/benefit && isort -c --settings-path ../shared/precommit-setup.cfg .
