name: (KS) Python tests

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/ks-pytest.yml'
  workflow_dispatch:

env:
  DEBUG: 1
  OIDC_OP_BASE_URL: https://tunnistus.test.hel.ninja/auth/realms/helsinki-tunnistus/protocol/openid-connect

jobs:
  pytest:
    name: Python tests
    runs-on: ubuntu-latest
    container: python:3.8-buster

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: kesaseteli
          POSTGRES_PASSWORD: kesaseteli
          POSTGRES_DB: kesaseteli

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache pip packages
        uses: actions/cache@v3
        env:
          cache-name: cache-pip-modules
        with:
          path: ~/.pip-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install gettext dependency
        run: |
          apt-get update
          apt-get install -y gettext

      - name: Install xmlsec1 dependency
        run: |
          apt-get update
          apt-get install -y xmlsec1 libsasl2-dev libssl-dev

      - name: Install dependencies
        run: cd backend/kesaseteli && pip install -r requirements.txt -r requirements-dev.txt

      - name: Compile messages
        run: cd backend/kesaseteli && python manage.py compilemessages

      - name: Run tests
        run: pytest backend/kesaseteli/ -ra -vv --doctest-modules --cov=. -n auto --dist loadfile --pyargs shared
        env:
          DATABASE_URL: postgres://kesaseteli:kesaseteli@postgres/kesaseteli
