name: Kesäseteli Test Environment Acceptance tests
on:
  # To be removed
  pull_request:
  schedule:
    # At half past every hour from 7-20 (finnish winter time)
    - cron: "0 5-18 * * *"
env:
  FRONTEND_URL: https://yjdh-kesaseteli-ui-test.agw.arodevtest.hel.fi
jobs:
  acceptance-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Acceptance tests for Test Environment
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
        id: commit
        run: |
          echo "::set-output name=commit_info::$(git log -1 --pretty=format:'%h%x09%an%x09%ad%x09%s')"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --check-files --production=false
      - name: Run TestCafe tests for Staging
        id: testcafe
        run: yarn --cwd kesaseteli/employer browser-test:ci
        env:
          GITHUB_WORKFLOW_NAME: ${{  github.workflow }}
          GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TESTCAFE_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TESTCAFE_SLACK_CHANNEL: "#yjdh-alerts"
          TESTCAFE_SLACK_USERNAME: GitHub-Alerts
      - name: Upload results
        run: |
          zip -r report.zip kesaseteli/employer/report/ > no_output 2>&1
          curl -s -H "Content-Type: application/zip" -H "Authorization: Bearer ${{secrets.NETLIFY_AUTH_TOKEN}}" --data-binary "@report.zip" https://api.netlify.com/api/v1/sites > response.json
          echo "REPORT_URL=$(cat response.json|python -c "import sys, json; print('https://' + json.load(sys.stdin)['subdomain'] + '.netlify.com')")" >> $GITHUB_ENV
        if: always() && steps.testcafe.outcome == 'failure'
      - name: link screenshots url to slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: GitHub-Alerts
          SLACK_TITLE: ${{ github.workflow }} have *FAILED* in ${{env.FRONTEND_URL}}!
          SLACK_CHANNEL: yjdh-alerts
          SLACK_MESSAGE: |
              *Check the testcafe report here: ${{env.REPORT_URL}}*
              The latest commit was:
              ```${{ steps.vars.outputs.sha_short }}```
              *NOTE* There is a chance that it was not deployed!
        if: always() && steps.testcafe.outcome == 'failure'
      - name: Create zip of screenshots and videos of failed tests to artifact for ${{env.FRONTEND_URL}}
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./frontend/kesaseteli/employer/report
        if: always() && steps.testcafe.outcome == 'failure'
